from student import Student
from course import Course
from student_course import StudentCourse
from boss import Boss
from boss_university import BossUniversity
from department import Department
from student_course import StudentCourse
from student_teacher import StudentTeacher
from teacher import Teacher
from teacher_course import TeacherCourse
from university import University
